import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Image Detector",
  description: "Generated by Next JS 14"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1 style={{textAlign:"center"}}>Next JS With Python</h1>
      <h2>Integrated Deep Learning</h2>
      <div className="container">
        <button><Link href="/">Homepage</Link></button>
      </div>
      {children}      
      </body>
    </html>
  );
}
